### ISSUE TITLE
ABBR for CDIA_CODE

### ISSUE THREAD

**Issue by SolidRockProgrammer** [australiangeomechanics/agsformat#16]
Does this item exist in reality?
HQ - HQ Casing

Consider adding 
PVC90 - 90 mm PVC Casing
and remove PVC

**Comment by digitalgeotechnics** [comment]
HWT casing is usually used for HQ series drilling.

Having said that, I'm pretty sure I've worked with drillers who used HQ drilling rods as casing when coring N series.  Although a "hack" I believe it meant they could get away with having less subs and rods about the place.  So perhaps HQ should remain an option.

FWIW this is a good reference for drill rod and casing sizes https://app.boartlongyear.com/brochures/CoringRodsCasingCatalog_Sep2020.pdf

agree re PVC

**Comment by digitalgeotechnics** [comment]
Following on, given "HQ Casing" doesn't technically exist, the term is potentially ambiguous.  Does it mean "the casing series that goes along with HQ series coring" (ie HWT) or "HQ rods used as casing".  "HWT" is unambiguous and should be used for the first situation.  Perhaps "HQ Casing" could be replaced by "HQ Rod" with description being "HQ rod used as casing"

**Comment by SThorin** [comment]
I like your last suggestion

**Comment by SolidRockProgrammer** [comment]
Applied in 1.2 excel
