### ISSUE TITLE
Consider adding more ABBR GEOL_SCL

### ISSUE THREAD

**Issue by SolidRockProgrammer** [australiangeomechanics/agsformat#20]
ML-MH	Low to High Liquid Limit SILT
OL-OH	Low to high Plasticity ORGANIC CLAYS and SILTS
SM-SC	Silty SAND to Clayey SAND

**Comment by SThorin** [comment]
Agree on SM-SC (dual classification as allowed by AS1726 6.1.6 but not keen on giving a full range on plasticity

**Comment by SolidRockProgrammer** [comment]
SM-SC added to excel 1.2

**Comment by SolidRockProgrammer** [comment]
CS-SM preexisted, so i will remove SM-SC.  we don't need both
