### ISSUE TITLE
GEOL_1ST and GEOL_2ST relate to soil only, not rock?

### ISSUE THREAD

**Issue by SolidRockProgrammer** [australiangeomechanics/agsformat#23]
GEOL Example sheet has it linked to soil and rock

**Comment by SThorin** [comment]
Structure exists in AS1726 both for soils and rocks. 
- for soils it is zoning (e.g. pockets, layers), defects, intermixing etc..
- for rock it is "geological structure" (and kept separate from fabric / texture). For instance you could describe the nonconforming nature of two strata (a.ka. with a missing layer in between), input the key joint sets after having done some stereonets, or refer to a fault name

These are therefore quite different. There are also fields which are not used very often in my experience, in particular the geological structure which is interpretive. Maybe we only keep 1ST/2ST for soil (adding "soil structure" in description) and use the 1REM/2REM for rock?

**Comment by SolidRockProgrammer** [comment]
*ST is for soil
Group note added to GEOL to define what to do for rock:
• GEOL_*ST are for soil structure only per AS 1726:2017:6.1.8. Rock structure is described in GEOL_*RTF, FRAC, DISC, or otherwise the concept of rock structure as described in AS 1726:2017:6.2.7 that trancends a single stratigaphy is outside the scope of AGS Format.
