### ISSUE TITLE
Purpose of GEOL's *SNQ and *RNQ fields 

### ISSUE THREAD

**Issue by digitalgeotechnics** [australiangeomechanics/agsformat#25]
Do we need guidance notes re the intention of these name qualifier fields?  As is, there is no guidance given to clarify if the information in these fields is to be new/stand alone information, or a summary of information provided in other fields in GEOL.

**Comment by digitalgeotechnics** [comment]
Example1:  `GLACIAL` in "GLACIAL MUDSTONE" - there is no GEOL heading for rock origin so `GLACIAL` is new information (unless it's also voluntarily repeated in the more generic *OTF or *REM fields).  Conversely, `VESICULAR` in "VESICULAR BASALT" has an AS1726 mandated home in *RTF (AS1726-2017 6.2.3.5).  In the latter example stating the presence vesicles happens twice in the data, resulting in data duplication which is something the data format generally tries to avoid.

**Comment by digitalgeotechnics** [comment]
Worth nothing as well that values in pick list GEOL_SNQ are general more summations than bespoke data values.

It's also worth nothing that *SNQ is the *primary* soil component qualifier.  This would imply that a *SNQ value of `siliceous` would be conveying a "gravelly SILICEOUS SAND".  There is thus no specific field for prefixing an entire soil name (eg `MY FAVOURITE` in "MY FAVOURITE silty SAND") - but is one actually required?

I've seen some consultants like to prefix a soil description with a colloquial name - eg "ROAD BASE/gravelly SAND" or "DECO/gravelly clayey SAND"  but AS1726-2017 6.1.3 would suggest that this sort of information should be included at the description, not right up front.

AS1726 6.1.3 *does* require the whole of a description to be prefixed with "FILL", where fill is encountered, however this is a description prefix, not a name prefix.  The presence of FILL is also stated in the GEOL_ORG* field, and algorithms compiling a description should prefix a description with "FILL" with reference to this field, rather than requiring data indicating the presence of fill to be duplicated into a second prefix field

**Comment by SolidRockProgrammer** [comment]
Created new heading GEOL_NCO, Colloquial material name, often prefixing full material name, example "roadbase"

**Comment by SolidRockProgrammer** [comment]
Tim S to add example description

**Comment by SolidRockProgrammer** [comment]
Need to consider if GEOL_FORM is same as GEOL_NCO.

Group notes:
as the use of GEOL_FORM will include for strata that do not have BGS Lexicon codes; for example, types of ANTHROPOGENIC GROUND such as embankment fill.

**Comment by StephenDurham** [comment]
In AGS 4.1.1 March 2022 GEOL_FORM does not have a picklist data type, so could easily be used to contain colloquial strata names. Perhaps we just don't need GEOL_NCO. That said it does give us the option for an alias, as we discussed contractors often use terms that are not official (where GEOL_FORM maybe more appropriate). As you can tell by my response, I am a bit on the fence.

**Comment by SolidRockProgrammer** [comment]
retain GEOL_NCO as it provides more flexibility to selectively report this data.

**Comment by SolidRockProgrammer** [comment]
Addition GEOL example not made
