### ISSUE TITLE
Edit to GEOL_*SNM heading description

### ISSUE THREAD

**Issue by digitalgeotechnics** [australiangeomechanics/agsformat#26]
The description of GEOL_*SNM - "Soil or non-rock name modification qualifier" - might be misleading?  It suggests that the field is used to modify/prefix the *name* (eg `MY FAVOURITE` in "MY FAVOURITE silty CLAY"), whereas the GEOL_SNM pick list values all relate to engineering modification of the *soil* properties (eg `lightly bound`).

Suggest the description be changed to simply "Soil modification" (noting also that the modification concept is not applicable for non-rock/non-soil materials)

**Comment by SolidRockProgrammer** [comment]
My first thought is, this is not very important and I don't mind either way. I don't want to change the heading name, but changing the description is fine.

**Comment by SThorin** [comment]
Are sure we cannot use for non-rock materials? If not sure would suggest renaming as "soil or non-rock modification qualifier" or "soil or non-rock modification"

**Comment by SolidRockProgrammer** [comment]
Description for GEOL_1SNM and GEOL_2SNM changed to "Soil or non-rock modification"
