### ISSUE TITLE
Boundary confidence ambiguity

### ISSUE THREAD

**Issue by digitalgeotechnics** [australiangeomechanics/agsformat#27]
Several groups have a CONF heading defined as "Defines the confidence of the base boundary; Sets the line type for layer lines within the description column".  

I have seen some organisations interpret the purpose of the field as being to indicate lack of absolute confidence regarding the depth of the base of the layer.  Under this approach I've seen the base of every layer in the augered portion of a auger hole be set as a dashed line, because you can't see down the hole to measure the exact depth of the layer change, therefore the "confidence" is lower than, say, the confidence one has when identifying the base of layers in a rock core.

However, the CONF pick list items include "well defined", "grading" and "poorly defined" which describe the geological characteristics of the boundary, which is an entirely different concept all together.

**Comment by digitalgeotechnics** [comment]
FWIW I think the purpose of this field should be the latter of the two presented in the OP - to describe the geological characteristics, not the uncertainty which may arise due to the drilling methodology which would largely be implicit for the whole of the interval of that drilling method.  

There may be other reasons for lower confidence of boundary depths though?  If we adopt the approach of "it's the geological characteristics" do we also need to provide a separate field for boundary uncertainty?

**Comment by SolidRockProgrammer** [comment]
Agreed approach in Teams call 5/11/21: change heading description to represent "geological characteristics of the boundary"
add a general note about this, not a group note since it is for many groups

**Comment by SolidRockProgrammer** [comment]
Applies this description in excel file: Geological characteristics of the boundary; Sets the line type for layer's bottom line

**Comment by SolidRockProgrammer** [comment]
Set to "Strata base boundary characteristics"
