### ISSUE TITLE
Add EPSG code to Description of ABBR for LOCA_GREF

### ISSUE THREAD

**Issue by SolidRockProgrammer** [australiangeomechanics/agsformat#37]

**Comment by digitalgeotechnics** [comment]
Done.

There doesn't appear to be an EPSG for GDA94 Zone 47

For reference:
* official EPSG website here https://epsg.org/
* origins of "EPSG" described here [https://en.wikipedia.org/wiki/EPSG_Geodetic_Parameter_Dataset](https://en.wikipedia.org/wiki/EPSG_Geodetic_Parameter_Dataset)

**Comment by hardreddata** [comment]
Perhaps https://epsg.io/6737 though one wonders what was wrong with 28347 as a number.

**Comment by SolidRockProgrammer** [comment]
Applied it
