### ISSUE TITLE
Schmidt Rebound Hardness rock test field test group

### ISSUE THREAD

**Issue by SolidRockProgrammer** [australiangeomechanics/agsformat#39]
### Discussed in https://github.com/australiangeomechanics/agsformat/discussions/13

<div type='discussions-op-text'>

<sup>Originally posted by **SolidRockProgrammer** September 24, 2021</sup>
Is this is common enough in Australia to add to AGS AU?
Is it an in situ, or lab test, or perhaps done in both locations.</div>

**Comment by SolidRockProgrammer** [comment]
Stephen says yes it is a field test too, we do have a lab group

**Comment by StephenDurham** [comment]
Added Group ISCH. Replicated from RSCH & trimmed the ISCH to be appropriate as a field test (LOCA - parent etc.)
Added notes about when RSCH and ISCH are to be used.

**Comment by SolidRockProgrammer** [comment]
I changed, added and reordered headings, to match the normal field test groups
ISCH_DPTH
ISCH_TESN
