### ISSUE TITLE
Abbreviation for Silty Sandy Clay is 808?

### ISSUE THREAD

**Issue by m-sams-artc** [australiangeomechanics/agsformat#47]
In the latest 'AGS.4.1.1.AU.1.2.-.released.2022-06-16' spreadsheet, the abbreviation for Silty Sandy Clay is listed as 808, which is the same as conglomerate. 99.9% sure this is just a bug - in the previous 'AGS-4.1.0-AU-1.1' spreadsheet, it was 207, which makes way more sense.

**Comment by SolidRockProgrammer** [comment]
Hi Sam
I don't see a problem:
![image](https://user-images.githubusercontent.com/38622251/176574366-97e6fb7a-bda5-4d0e-90f6-450d1f63b606.png)
regards
Phil

**Comment by m-sams-artc** [comment]
Ok, thanks for checking. Maybe some accidental copy-pasting from our side. Apologies - I might have jumped the gun. Will download the unaltered spreadsheet again.
